### ISSUE TITLE
Refactor Printer

### ISSUE THREAD

**Issue by icsaszar** [ebkalderon/tower-lsp#128]
I didn't really know how to name this issue, but currently there are some things that could be improved in `delegate/printer.rs`.

### Duplicated code for getting the next request id
First it would be nice to get the request id number in one function and not have it duplicated in `register_capability`, `unregister_capability`, `apply_edit`.

The simplest solution would probably by to just put it a separate method (`Printer::get_next_request_id()`) in `Printer`, but  I feel like it would be better to get the request id in the function/method that generates the actual request (currently `make_request()`).

### Redundant serialization and deserialization in `make_request` and `make_notification`
Second, I would be curious if we could skip the serialization, deserialization then serialization of params in `make_request` and `make_notification`.

Depending on the input params, I think that the problem could be solved with some string manipulation (serializing the rpc request, params and then inserting params into the serialized request), or by defining custom structs or one enum (`RegisterCapabilityRpcRequest`, `ApplyWorkspaceEditRpcRequest`) that take the right parameter (e.g. `RegistrationParams`, `ApplyWorkspaceEditParams`, `UnregistrationParams`, etc.) and serialize directly.

The second option seems quite doable since both`make_request` and `make_notification` return `String`, with the usual downside of extra maintenance (of the said structs) to keep up with `lsp_types` and `jsonrpc-core`. The first one comes with the risk of introducing bugs and is really hacky, but it could probably be hacked into the current implementation with minimal changes and maintenance afterwards.

Edit: Maybe implementing a trait `RpcServerRequest : Serialize` for the lsp types (`RegisterCapability`, `UnregisterCapability`, etc) that offers a uniform interface for serialization (hard code rpc version in a default implementation and take id as param in the actual serialization method) would be the cleanest solution.

Progress on #13 probably affects this issue, since it also involves changes to printer. Depending on the discussion here and the status of #13 I'd be happy to help with the refactoring.

**Comment by icsaszar** [comment]
@ebkalderon I managed to solve the second issue quite easily with a generic struct. You can check out the changes at [printer-refactor](https://github.com/icsaszar/tower-lsp/tree/printer-refactor). I don't feel like it's pull request ready yet since I wrote some tests to see if it works and they because the fields are serialized in a different order (which should be fine for clients but it would be nice to know why).

**Comment by ebkalderon** [comment]
Good suggestions, @icsaszar! I definitely think that the redundant serialization in `make_request()` and `make_notification()` needs to go away.

You beat me to it, as I was about to agree with you on the custom struct approach. 😄 I just took a look at your branch, and it looks pretty good, although I'd probably just call it something like `RawRequest` and have it defined directly in the `make_request()` function body to make it clear it's an implementation detail of that function. As for the ordering, I think it might have something to do with how `jsonrpc_core::types::params::Params` handles the serialization of fields. Notice how `Params::Map` converts structs into a heterogenous [`serde_json::map::Map<String, Value>`](https://docs.rs/jsonrpc-core/14.0.5/jsonrpc_core/types/params/enum.Params.html#variant.Map), which may or may not preserve entry ordering depending on whether the crate is build with the `"preserve_order" feature or not.
 
In regards to incrementing the request ID, I disagree that we should put that directly into the `make_request()` function. I would prefer that this function remain a pure data transformation from inputs to outputs without any side effects, if possible, to make it easy to test.

I do agree with you that we should abstract over the `request_id` field and reduce the duplication of code, though. Currently, it's not too bad (just one line), but once we move forward on #13, it will become important. I'm wondering whether the optimal solution would be to create a `Router` struct that resides inside of `Printer` (likely to be renamed `Client`) which would handle the request/response routing to and from the client and, in turn, would contain the logic for incrementing the `request_id` field as necessary.

**Comment by ebkalderon** [comment]
Speaking of, I would like to request that we hold off on #13 for a brief moment so we can switch all of the notification methods on the `LanguageServer` trait to `async fn` (first suggested [here](https://github.com/ebkalderon/tower-lsp/issues/13#issuecomment-589995913)). This would be a prerequisite for #13, which would allow us to `.await` on requests in those method bodies once we have proper client request handling.

**Comment by ebkalderon** [comment]
BTW, it looks like `jsonrpc-core` builds `serde_json` without the `"preserve_order"` feature enabled ([source](https://github.com/paritytech/jsonrpc/blob/master/core/Cargo.toml#L25)), which means it uses a `BTreeMap` under the hood ([source](https://docs.rs/serde_json/1.0.42/src/serde_json/map.rs.html#24-26)), causing the fields to be reordered.

**Comment by icsaszar** [comment]
Seems, good to me. I'll move the structs in the functions, remove the failing test and open a pull request so we can better discuss further changes (like testing).
