### ISSUE TITLE
Consider supporting proposed semanticHighlight notification

### ISSUE THREAD

**Issue by ebkalderon** [ebkalderon/tower-lsp#146]
The `textDocument/semanticHighlight` server-to-client notification is a proposed addition to the Language Server Protocol which would allow servers to perform syntax highlighting of open text documents ([upstream issue](https://github.com/microsoft/language-server-protocol/issues/513), [prototype JS implementation](https://github.com/microsoft/vscode-languageserver-node/pull/367), [relevant `lsp-types` PR](https://github.com/gluon-lang/lsp-types/pull/127)).

Since this is a proposed protocol feature currently not in the specification yet, we might need to gate it with a "proposed" feature flag, similar to what `lsp-types` does for the feature currently.

This feature is fairly low priority, possibly below #145, but would nonetheless be nice to have.

**Comment by GalAster** [comment]
I also need this, can we add the  `"proposed"` feature?

**Comment by ebkalderon** [comment]
Resolved in #270 under the "semantic tokens" feature of LSP 3.16! :tada:
