### ISSUE TITLE
Implement support for $/progress

### ISSUE THREAD

**Issue by silvanshade** [ebkalderon/tower-lsp#176]
It would be nice to be able to support [progress notifications](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#progress). I haven't looked into what sort of modifications would be needed for this but it seems like it should have an issue for the sake of completeness.

**Comment by ebkalderon** [comment]
Thanks for opening this issue! It's a good idea to track this for the sake of completeness, regardless of priority.

**Comment by ebkalderon** [comment]
I think it should be pretty trivial to expose a server-to-client progress notification API in the form of a new `Client` method which uses `ProgressToken`s to report progress. However, I wonder whether we should also design higher-level API abstractions with better ergonomics, perhaps like this?

```rust
#[derive(Default)]
pub struct ProgressDetails {
    pub title: String,
    pub message: Option<String>,
    pub cancellable: Option<bool>,
}

impl Client {
    /// Wraps a stream and reports `$/progress` notifications to the client, using `count` to calculate percentage.
    pub fn progress_count<T, S>(&self, stream: S, count: u64, details: ProgressDetails) -> impl Stream<Item = T> + Send + Unpin + '_
    where
        S: Stream<Item = T> + Send + Unpin;
}
```

**Comment by ebkalderon** [comment]
In addition, perhaps we could return a more manual API like this:

```rust
impl Client {
    pub fn progress<T, M>(&self, title: T, message: M) -> Progress
    where
        T: Into<String>,
        M: Into<Option<String>>;
}

pub struct Progress<P = Infinite, C = Cancellable> { ... }

impl<C> Progress<Infinite, C> {
    pub fn with_percentage(self, percentage: u32) -> Progress<Bounded, C>;
}

impl<P> Progress<P, NotCancellable> {
    pub fn cancellable(self, cancel_enabled: bool) -> Progress<P, Cancellable>;
}

impl<P, C> Progress<P, C> {
    pub async fn begin(self) -> Result<ProgressStarted<P, C>>;
}

pub struct ProgressStarted<P, C> { ... }

impl ProgressStarted<Infinite, NotCancellable> {
    pub async fn report(&self, message: Option<String>) -> Result<()>;
    pub async fn finish(self, message: Option<String>) -> Result<()>;
}

impl ProgressStarted<Bounded, NotCancellable> {
    pub async fn report(&self, percentage: u32, message: Option<String>) -> Result<()>;
}

impl ProgressStarted<Infinite, Cancellable> {
    pub async fn report(&self, message: Option<String>, cancel_enabled: bool) -> Result<()>;
}

impl ProgressStarted<Bounded, Cancellable> {
    pub async fn report(&self, percentage: u32, message: Option<String>, cancel_enabled: bool) -> Result<()>;
}

impl<P, C> ProgressStarted<P, C> {
    pub async fn finish(&self, message: Option<String>) -> Result<()>;
}
```

The final usage would be quite ergonomic, and also type safe:

```rust
impl LanguageServer for Backend {
    async fn completion(&self, _: CompletionParams) -> Result<Option<CompletionResponse>> {
        let progress = self
            .client
            .progress("retrieving completions", None)
            .with_percentage(0)
            .begin()
            .await?;

        for x in something {
            // Do some work...
            let percentage = ...
            progress.report(percentage, Some("reticulating splines".into()).await?;
        }

        progress.finish().await?;

        // ...
    }
```

**Comment by ebkalderon** [comment]
Now, according to the specification, it's technically possible for a `WorkDoneProgressBegin` or `WorkDoneProgressReport` notification to start out with a `percentage` and/or `cancellable` field, but as soon as either or both of these are omitted by the server, the client will ignore them and switch to treating the progress as infinite or not cancellable from then on.

As such, maybe we could also add methods to the `impl ProgressStarted<..., ...>` blocks like:

```rust
impl<C> ProgressStarted<Bounded, C> {
    pub fn infinite(self) -> ProgressStarted<Infinite, C>;
}

impl<P> ProgressStarted<P, Cancellable> {
    pub fn not_cancellable(self) -> ProgressStarted<P, NotCancellable>
}
```

These methods would allow the user to switch an active progress bar over to being infinite and/or not cancellable at any point, and this would downgrade the `ProgressStarted` type, changing the type signature of the `report()` method to match.

**Comment by TimJentzsch** [comment]
If you're looking for contributions, I'd be interested in taking a stab at implementing this.
However I have to say that I am rather new at LSP and async Rust.

**Comment by ratmice** [comment]
FWIW, I implemented it in the following commit just using send_request/send_notification + lsp-types API.
So it doesn't technically seem to *require* further support methods above and beyond what tower already implements it seems.

https://github.com/ratmice/nimbleparse_lsp/commit/c403506bf459fbe60ee14e455c4119c87a870ef6

**Comment by oxalica** [comment]
Is there any progress to this? This functionality is quite necessary when the loading costs more than seconds.

**Comment by ratmice** [comment]
@oxalica I assume it might not be a high priority since you can implement it in terms of the following without the additional ergonomics/friendlier API, as in the commit referenced in my previous comment here.

* https://docs.rs/tower-lsp/latest/tower_lsp/struct.Client.html#method.send_request
      https://docs.rs/lsp-types/latest/lsp_types/request/enum.WorkDoneProgressCreate.html
* https://docs.rs/tower-lsp/latest/tower_lsp/struct.Client.html#method.send_notification
     https://docs.rs/lsp-types/latest/lsp_types/notification/enum.Progress.html
     https://docs.rs/lsp-types/latest/lsp_types/notification/enum.WorkDoneProgressCancel.html

So if it is really necessary it isn't too difficult to implement on top of what is already working today without the details discussed above.

**Comment by dalance** [comment]
I implemented progress by reference to nimbleparse_lsp. ( Thanks @ratmice ! )

https://github.com/dalance/veryl/commit/344558358c1cb6cc5ba6c59d927ed6b9634d5e54

The implementation is very simple.

* Add async functions ( `progress_start`, `progress_report` and `progress_done` ) to your backend.
* Call the functions where you want to.

**Comment by ebkalderon** [comment]
This ticket is currently conflating two different types of progress described by the LSP specification:

1. Client initiated progress
    1. The **client** includes a `.work_done_progress_params.work_done_token` field in the `"params"` given to the **server**.
    2. The **server** sends back `$/progress` begin/report/end notifications to the **client** using this `work_done_token` value.
2. Server initiated progress
    1. The **server** sends a `window/workDoneProgress/create` request (with a server-generated `WorkDoneToken`) to the **client**.
    2. If it succeeds, the **server** sends `$/progress` begin/report/end notifications to the **client** using the same `WorkDoneToken`.
    3. If it fails, the **server** must not send progress notifications using that `WorkDoneToken` at all.
    4. The **client** may send a `window/workDoneProgress/cancel` notification with a `WorkDoneToken`  to the **server**.

I'm thinking this issue should be split into three separate tickets for better tracking:

1. Support client initiated progress
   * Introduce an API resembling [this proposal](https://github.com/ebkalderon/tower-lsp/issues/176#issuecomment-1058827918). This lets the server send a stream of `$/progress` notifications to the client using a client-issued `WorkDoneToken`.
2. Support server initiated progress
   * Add a `Client::server_progress()` method which performs the following steps.
     1. Generates a new unique `WorkDoneToken`.
     2. Sends a `window/workDoneProgress/create` request to the client.
     3. If it succeeds, it calls into `Client::progress()` with the server-generated `WorkDoneToken`, reusing previous work.
     4. If it fails, it short-circuits with an `Err(_)` and no `$/progress` stream may be initiated.
   * Add a `LanguageServer::work_done_progress_cancel()` trait method (corresponding to `window/workDoneProgress/cancel`), from which the server may cancel ongoing progress.

Does this sound reasonable to you folks?

**Comment by ratmice** [comment]
Seems good to me, I wasn't actually aware of client side progress!
