### ISSUE TITLE
Server doesn't exit on receiving exit notification

### ISSUE THREAD

**Issue by adituv** [ebkalderon/tower-lsp#239]
On receiving an exit notification, the server does not return until the next well-formed message is received, or the input is closed.

This might not affect much for regular usage on stdin, but likely will for a TCP listener.  It also causes the tests I am writing using [lsp-test](https://hackage.haskell.org/package/lsp-test) to hang.

<details>
<summary><b>Sample session.  Click to expand</b></summary>

```
stdout>  INFO language server initialized
stdout> Content-Length: 86
stdout> 
stdout> {"jsonrpc":"2.0","result":{"capabilities":{"documentFormattingProvider":true}},"id":1}

 stdin> Content-Length: 46^M
 stdin> ^M
 stdin> {
 stdin>     "jsonrpc": "2.0",
 stdin>     "method": "exit"
 stdin> }

stdout>  INFO exit notification received, stopping

 stdin> Content-Length: 0^M
 stdin> ^M

stdout> ERROR failed to decode message: unable to parse JSON body: EOF while parsing a value at line 1 column 0
stdout> Content-Length: 75
stdout> 
stdout> {"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}

 stdin> Content-Length: 2^M
 stdin> ^M
 stdin> {}

stdout> ERROR language server has exited
stdout>  INFO Successfully completed
```
</details>

**Comment by ebkalderon** [comment]
Thank you for reporting this, @adituv! This may very well be a zero-length message parsing bug, if the `ERROR failed to decode message: unable to parse JSON body: EOF while parsing a value at line 1 column 0` log message is to be believed. I'll have to dig deeper on this one.

**Comment by ebkalderon** [comment]
I've opened PR #271 which fixes the parse error seen in the sample session posted above. Feel free to try it out and confirm whether it resolves the problem!
