### ISSUE TITLE
Add Support for Proposed Features

### ISSUE THREAD

**Issue by sno2** [ebkalderon/tower-lsp#329]
Hello, it would be great if we could have support for proposed features via a Cargo feature flag.  This is currently what [`gluon-lang/lsp-types`](https://github.com/gluon-lang/lsp-types) is doing to allow for using the latest features in the [LSP specification version 3.17](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/) (e.g. inlay hints).  They simply block all proposed features to the spec under a `proposed` cargo feature without any guarantees on breaking changes under this flag.

**Comment by sno2** [comment]
I am also not saying that you should implement these features yourself. I am planning on implementing inlay hints because the Deno LSP is currently blocked by no support for inlay hints in `tower-lsp`.

**Comment by sno2** [comment]
Hey @ebkalderon thanks for working on this project! Do you have any comment on this?

**Comment by ebkalderon** [comment]
Sorry for the delayed response! Yeah, I wholeheartedly agree that matching the `proposed` feature of the `lsp-types` crate in this project would be a good idea, especially for supporting inlay hints and other features not yet in the official specification. I left a review on the linked PR with some minor feedback, but it looks great overall.

**Comment by ebkalderon** [comment]
Closed in #330 and released in 0.17.0.
