### ISSUE TITLE
`tower_lsp::ClientSocket` is (potentially) missing some functionality from `lspower::MessageStream` 

### ISSUE THREAD

**Issue by rockstar** [ebkalderon/tower-lsp#341]
In influxdata/flux-lsp#427, the flux-lsp moved from `lspower` to `tower-lsp` because the merge had occurred. The reason we had used `lspower` in the first place is because we needed to be able export the lsp server via wasm. We have a wasm interface that looks like this (expressed in TypeScript):

```
interface LspServer {
  run(): Promise<void>;
  send(message: String): Promise<String>;
  onMessage(handler: (message: String) => String): void;
}
```

The idea here was that you could request things from the server via `send`, and any time that the server needed to initiate diagnostics, logs, notifications, etc. via the `onMessage` handlers. The way we implemented this is something similar to this (you can read the full source in the PR/repo)

```
let (service, messages) = LspService::new(...);

while let Some(msg) = messages.next().await {
  ...some code for handling msg...
  for h in onMessageHandlers {
    h.call1(msg);
  }
}
```

Somewhere between the change from `lspower::MessageStream` to `tower_lsp::ClientSocket`, that message firing from the server is broken. While trying to dig into the issue, a lot of the introspection isn't possible because `ClientSocket` has a lot of private interfaces (which probably isn't related to the issue, but maybe something to consider for debugging going forward). What am I missing? How did the interface change so that `messages.next().await` doesn't ever loop, no matter how many messages the server sends to the client.

**Comment by ebkalderon** [comment]
Thanks for opening this ticket! If you check the `Stream` implementation of `ClientSocket` today ([source](https://github.com/ebkalderon/tower-lsp/blob/a8f0d01/src/service/client/socket.rs#L41-L56)), it delegates down into the underlying `futures::channel::mpsc::Receiver<_>` implementation of `Stream`. This is pretty much the same as how the old `Client` and `MessageStream` worked, albeit with a new abstraction around it.

> How did the interface change so that `messages.next().await` doesn't ever loop, no matter how many messages the server sends to the client.

Do you think you could elaborate on what you mean by this? In the code snippet above, I cannot see how `service` is being driven. The `LspService` must be actively emitting server-to-client messages for `messages.next().await` to yield them, and since there isn't any `service.call(...).await` nor is `service` passed into `Server::new`, I can't understand how the loop would ever progress as described. I'd love if you could provide more details!

**Comment by rockstar** [comment]
Thanks for the reply. I've been fighting trying to solve this bug for quite a bit; I don't see that much functional difference.

We have an [exported `run` function](https://github.com/influxdata/flux-lsp/blob/master/src/wasm.rs#L182) that essentially fakes an event loop and runs forever. That calls `server.processor.process().await` (with some error handling). Our [`send` function](https://github.com/influxdata/flux-lsp/blob/master/src/wasm.rs#L115) is [where `service.call` is called](https://github.com/influxdata/flux-lsp/blob/master/src/wasm.rs#L129), but I didn't think that'd have much to do with messages originating from the server; you asking about it makes me wonder if I need to be looking at this solution holistically, and potentially evaluating whether or solution is hacky or not.

**Comment by silvanshade** [comment]
@rockstar I'm not really sure why the approach you described worked before but doesn't work now, but I am wondering if the problem might go away if you could avoid using the custom `LspServer` interface and instead set things up through `Server::new` as usual.

In the case of a wasm target, I believe you should be able to use the web [Streams API](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API). There is a [wasm-streams](https://crates.io/crates/wasm-streams) crate that provides adapters between the Streams API from `web-sys` and the usual `futures` Streams, along with impls for `AsyncRead` and `AsyncWrite`, which you will need for connecting everything up with `Server::new`.

Below is a quick sketch that compiles but doesn't really do anything, although perhaps it can give you some ideas of how to proceed. (For your actual implementation I suppose you would want to implement some sort of custom (web) streams that let you pass messages in and observe the responses.)

```rust
#![cfg(target_arch = "wasm32")]

use flux_lsp::LspServer;
use futures_util::stream::{TryStreamExt};
use js_sys::Uint8Array;
use tower_lsp::{LspService, Server};
use wasm_bindgen_test::*;
use wasm_bindgen::{prelude::*, JsCast};
use wasm_streams::readable::*;
use web_sys::TextEncoder;

#[wasm_bindgen(inline_js = "
export function new_readable_stream_from_array(chunks) {
    return new ReadableStream({
        start(controller) {
            for (let chunk of chunks) {
                controller.enqueue(chunk);
            }
            controller.close();
        }
    });
}")]
extern "C" {
    pub fn new_readable_stream_from_array(chunks: Box<[JsValue]>) -> sys::ReadableStream;
}

wasm_bindgen_test_configure!(run_in_browser);

#[wasm_bindgen_test]
async fn it_works() {
    let message = r#"{"method": "initialize", "params": { "capabilities": {}}, "jsonrpc": "2.0", "id": 1}"#;
    let message_with_headers = format!("Content-Length: {}\r\n\r\n{}", message.len(), message);

    let bytes: Vec<u8> = TextEncoder::new().unwrap().encode_with_input(&message_with_headers);
    let bytes: Uint8Array = bytes.as_slice().into();
    let bytes: JsValue = bytes.into();

    let stdin = new_readable_stream_from_array(vec![bytes].into_boxed_slice());
    let stdin = ReadableStream::from_raw(stdin);
    let stdin = stdin
        .into_stream()
        .map_ok(|value| value.dyn_into::<Uint8Array>().unwrap().to_vec())
        .map_err(|_err| std::io::Error::from(std::io::ErrorKind::Other))
        .into_async_read();

    let stdout = wasm_streams::writable::sys::WritableStream::new();
    let stdout = wasm_streams::WritableStream::from_raw(stdout);
    let stdout = stdout.try_into_async_write().unwrap();

    let (service, messages) = LspService::new(|client| LspServer::new(Some(client)));
    Server::new(stdin, stdout, messages).serve(service).await;
}
```

**Comment by silvanshade** [comment]
The wasm-based project that I linked to above is now a fairly complete example which fully demonstrates how to use `tower-lsp` with the intended API in a wasm context. I'd be happy to answer any questions about how that was set up but otherwise I think it's safe to close this since the original motivation was to be able to use `tower-lsp` for a wasm target.

**Comment by rockstar** [comment]
I'm not sure I agree that the bug is fixed. Sure, you've provided a workaround, but there's a disconnect where "what worked then doesn't work now" in an absolutely public api. The workaround is definitely something to explore, but this would require an re-architecture of a large portion of more than one application. As it stands, the migration from `lspower` to `tower-lsp` is a no-go for us.
