### ISSUE TITLE
support inlineValue method and Inlay Hint Request

### ISSUE THREAD

**Issue by OceanBelongsToMe** [ebkalderon/tower-lsp#352]

**Comment by ebkalderon** [comment]
Seems like a big omission! These should both be added for the next major release.

**Comment by ebkalderon** [comment]
Hmm, it seems that `lsp-types` still marks inlay hint requests as `proposed` despite being officially adopted into the spec (https://github.com/gluon-lang/lsp-types/issues/251) and also lacks support for inline values entirely (https://github.com/gluon-lang/lsp-types/issues/252). I'll have to submit a pull request against `lsp-types` to have this remedied.

**Comment by ebkalderon** [comment]
I've opened gluon-lang/lsp-types#255 to add support for this, as well as other missing functionality (except for notebook support, which seems is already being worked on by someone else).

**Comment by ebkalderon** [comment]
Updated `lsp-types` to 0.94.0 in #367. Will update the `LanguageServer` trait to enable 3.17 features into `tower-lsp` soon.
