### ISSUE TITLE
Implement support for diagnostic requests on server

### ISSUE THREAD

**Issue by ebkalderon** [ebkalderon/tower-lsp#374]
The `LanguageServer` trait is missing the following requests:

- [ ] `textDocument/diagnostic`
- [ ] `workspace/diagnostic`

The `Client` struct is also missing the following requests:

- [ ] `workspace/diagnostic/refresh`

These request types were added in LSP 3.17.0, but `lsp-types` unfortunately doesn't support them. This should have landed in `lsp-types` 0.94.0, but was missed in https://github.com/gluon-lang/lsp-types/pull/255. I've opened https://github.com/gluon-lang/lsp-types/pull/258 to address this omission.

**Comment by ebkalderon** [comment]
Unassigning myself as this ticket is blocked on https://github.com/gluon-lang/lsp-types/pull/258 currently.

**Comment by meetmangukiya** [comment]
does there exist any branch of tower-lsp with implementation utilizing https://github.com/gluon-lang/lsp-types/pull/258?

**Comment by ebkalderon** [comment]
@meetmangukiya Not at the moment, sadly. It should be pretty trivial to add after the PR is merged, though!

**Comment by ebkalderon** [comment]
Upstream PR was only just merged! :tada: A maintenance release of `tower-lsp` containing the changes should come shortly.

**Comment by ebkalderon** [comment]
@meetmangukiya Alright, `tower-lsp` 0.20.0 and `tower-lsp-macros` 0.9.0 have been released to crates.io. This release includes full support for diagnostic requests. :rocket:

**Comment by meetmangukiya** [comment]
nice, thanks!
