### ISSUE TITLE
Header must provide a Content-Length property

### ISSUE THREAD

**Issue by OceanBelongsToMe** [ebkalderon/tower-lsp#410]
Client Language Server Example: connection to server is erroring. Header must provide a Content-Length property. {"{\"jsonrpc\"":"\"2.0\",\"result\":{\"contents\":\"## test1\\n\\n- test\\n | a | b | c |\\n | --- | --- | --- |\\n | ss | ss | ss |\\n | ss | ss | ss |\",\"range\":{\"end\":{\"character\":6,\"line\":7},\"start\":{\"character\":6,\"line\":7}}},\"id\":25}Content-Length: 39"} Shutting down server.

<img width="456" alt="image" src="https://github.com/ebkalderon/tower-lsp/assets/22573382/88fdfc9d-0a00-4d82-b813-e2ddda15c632">

**Comment by OceanBelongsToMe** [comment]
```rust
let (service, socket) = LspService::new(|client| Backend {
        client,
        trie: Default::default(),
    });
    Server::new(stdin, stdout, socket).serve(service).await;
```

**Comment by attila-lin** [comment]
I think you may printed something.

remove all `print`/`dbg` if you use `stdio/stdout`

**Comment by OceanBelongsToMe** [comment]
> I think you may printed something.
> 
> remove all `print`/`dbg` if you use `stdio/stdout`

yes you are right, thanks for your help！
