### ISSUE TITLE
Convert to std::future and async/await

### ISSUE THREAD

**Issue by ebkalderon** [ebkalderon/tower-lsp#58]
With async/await stabilizing in [Rust 1.39.0](https://blog.rust-lang.org/2019/11/07/Rust-1.39.0.html), this library should be ported to use the new syntax and switch to `std::future::Future`. This should involve upgrading `tower-service` to version 0.3.0alpha.2 and switching away from `jsonrpc_core` to the brand-new [`jsonrpsee`](https://github.com/paritytech/jsonrpsee) crate.

Unfortunately, `jsonrpsee` does not provide a stdio transport at the time of writing. Since this is a hard requirement for virtually all LSP servers, we will have to wait until support is implemented.

**Comment by ebkalderon** [comment]
@icsaszar FYI, I have an experimental branch with async/await support [here](https://github.com/ebkalderon/tower-lsp/compare/convert-to-async-await). Creating a pull request from this and merging it would affect your efforts on #100, though, so I'm waiting a bit. Feel free to read through the commit messages and see what has changed!

**Comment by icsaszar** [comment]
@ebkalderon  You can go ahead and merge it if you're ready, I was waiting for feedback on #100, so I haven't started yet.

**Comment by ebkalderon** [comment]
Okay, sounds good! Do you personally find the new trait API with `async-trait` acceptable? Would any of the changes have any negative impact on your current projects?

**Comment by ebkalderon** [comment]
@icsaszar This issue will be closed as a result of merging #101, but feel free to leave your comments in a new issue if you have any concerns for your project! I don't plan on making a brand-new release on Crates.io until #100 is resolved as well.
