### ISSUE TITLE
Add code to handle incremental text updates

### ISSUE THREAD

**Issue by Timmmm** [ebkalderon/tower-lsp#72]
Nice project! I can't use it yet because I really only need [go to type definition](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_typeDefinition), but I'm keeping an eye on this.

Anyway, it would be very good if you could add code to the crate that (optionally) lets users have the incremental text updates handled for them. It's quite a pain to get right yourself because everything is done by line and row indices and they are measured in UTF-16 code points even though the actual text is sent as UTF-8! Yes, it is ridiculous.

**Comment by ebkalderon** [comment]
Thanks for the kind words and feedback! Have you thought of using [codespan](https://docs.rs/codespan/0.5.0/codespan/index.html) and [codespan-lsp](https://docs.rs/codespan-lsp/0.5.0/codespan_lsp/), by any chance? The latter crate in particular should handle most of the conversions you describe, and it's what I personally use in my own LSP projects, including incremental text updates. With that said, I'm open to potentially "baking in" this sort of functionality into the project as an optional addition.

As for [`textDocument/definition`](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#textDocument_definition), I suppose that API addition will have to come in the next few releases. 😄

**Comment by ebkalderon** [comment]
Both `textDocument/definition` and `textDocument/typeDefinition` are on the list in #10. Hopefully I can knock them out over the next several days. If you would like to submit a pull request yourself, of course, that would also be most welcome.

**Comment by Timmmm** [comment]
Thanks for the links to `codespan` - didn't know about that. Since I wrote this I also discovered that `rust-analyzer` has its LSP stuff as a generic crate. [Here's an example](https://github.com/rust-analyzer/lsp-server/blob/master/examples/goto_def.rs). However they don't provide a nice trait like you do, so I'd definitely rather use this if it were complete.

**Comment by ebkalderon** [comment]
@Timmmm I've just merged in pull request #76, which implements goto declaration, goto definition, and goto type definition support. I hope to have a new release out on Crates.io fairly soon! Feel free to depend directly on the `master` branch in the meantime, if your project allows it and you're eager to begin iterating. ☺️

**Comment by Timmmm** [comment]
Ah cool, thanks! I'll give it a go.

**Comment by ebkalderon** [comment]
@Timmmm Please alert me to any glaring issues come up before the next release! I'll do my best to get in some quick fixes before publishing to Crates.io, if deemed necessary.

**Comment by ebkalderon** [comment]
@Timmmm Version 0.6.0 has just been published to Crates.io with support for goto declaration, goto definition, and goto type definition.

**Comment by ebkalderon** [comment]
We are currently depending on an old version of `lsp-types` (0.68 vs. 0.70, at the time of writing) because `codespan-lsp` hasn't been updated to support the latest version of `lsp-types` (see brendanzab/codespan#163). Once this is updated, I think we can update our `lsp-types` dependency to the latest version and close this issue as invalid.

**Comment by ebkalderon** [comment]
Closed by #105, which gives us access to the latest `lsp-types` and therefore compatibility with the latest `codespan-lsp`.

**Comment by Timmmm** [comment]
Finally got around to retrying this - haven't got incremental code changes to work yet (waiting to see what comes of https://github.com/brendanzab/codespan/issues/249), but Go To Definition works perfectly, thanks!

**Comment by ebkalderon** [comment]
@Timmmm That's fantastic news! Glad it works for you. 🤗 I'm still waiting to see what the future of `codespan` will actually be, given that @brendanzab has been refactoring the repo quite a bit. I'm sure some solution for your needs will still exist though.
