### ISSUE TITLE
Add support for completionItem/resolve request on server

### ISSUE THREAD

**Issue by ebkalderon** [ebkalderon/tower-lsp#9]
The `LanguageServer` trait is currently missing support for the [`completionItem/resolve`](https://microsoft.github.io/language-server-protocol/specification#completionItem_resolve) request which is often used in conjunction with the `textDocument/completion` request (see #10).

**Comment by icsaszar** [comment]
Probably needs #100 because method must return a `CompletionItem` and I think it wouldn't be nice to return a `CompletionItem::default()`.

**Comment by ebkalderon** [comment]
We definitely would have to return a JSON-RPC error in that case, not a `CompletionItem::default()`, because doing so would be semantically incorrect.
